---
- set_fact:
    append_questions:
      - "Set the system timezone to PDT (America/Los_Angeles)."

- name: Ensure timezone is UTC by default
  file:
    src: /usr/share/zoneinfo/UTC
    dest: /etc/localtime
    state: link
    force: yes

- set_fact:
    questions: "{{ questions }}+{{ append_questions }}"
