---
- name: Set hostname in /etc/hostname
  copy:
    content: "interview.local\n"
    dest: /etc/hostname
  register: h1

- name: Ensure public IP is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ ansible_default_ipv4.address }} interview.local interview"
    regexp: "{{ ansible_default_ipv4.address }}"
  register: h2

- name: Run hostname change
  shell: hostname interview.local
  when: "h1|changed or h2|changed"
